import "C:\Program Files\Microsoft Platform SDK\include\prsht.idl";
import "C:\Program Files\Microsoft Platform SDK\include\mshtml.idl";
import "c:\program files\microsoft platform sdk\include\dimm.idl";
import "C:\Program Files\Microsoft Platform SDK\include\mshtmhst.idl";
import "c:\program files\microsoft platform sdk\include\docobj.idl";
import "C:\Program Files\Microsoft Platform SDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Platform SDK\include\objsafe.idl";

[
	object,
	uuid(9E043877-CE0F-43B7-972B-F3BCD32DB992),
	dual,
	helpstring("ILdapAttribute Interface"),
	pointer_default(unique)
] 
#line 16 "c:\\source\\excel ldap search\\ldapquery\\ldapattribute.h"
interface ILdapAttribute : IDispatch {
#line 18 "c:\\source\\excel ldap search\\ldapquery\\ldapattribute.h"
	[propget,id(1),helpstring("property Name")] HRESULT  Name([out,retval] BSTR *pVal );
	[propget,id(2),helpstring("property Value")] HRESULT  Value([out,retval] BSTR *pVal );
	[id(3),helpstring("method IsValid")] HRESULT  IsValid([out,retval] SHORT *valid);
};

[
	object,
	uuid(D7CE424E-C72D-4C68-9B27-E6DA2D4F6268),
	dual,
	helpstring("ILdapSearchResult Interface"),
	pointer_default(unique)
] 
#line 17 "c:\\source\\excel ldap search\\ldapquery\\ldapsearchresult.h"
interface ILdapSearchResult : IDispatch {
#line 19 "c:\\source\\excel ldap search\\ldapquery\\ldapsearchresult.h"
	[propget,id(1),helpstring("property DN")] HRESULT  DN([out,retval] BSTR *pVal );
	[id(2),helpstring("method IsValid")] HRESULT  IsValid([out,retval] SHORT *bValid);
	[id(3),helpstring("method GetFirstAttribute")] HRESULT  GetFirstAttribute([out,retval] ILdapAttribute **attribute );
	[id(4),helpstring("method GetNextAttribute")] HRESULT  GetNextAttribute([out,retval] ILdapAttribute **attribute );
	[id(5),helpstring("method GetAttributeByName")] HRESULT  GetAttributeByName([in] BSTR name, [out,retval] ILdapAttribute **attribute );
};

[
	object,
	uuid(4F43CF43-E86F-4C46-A6EB-A2BCF36F3781),
	dual,
	helpstring("ILdapSearchResults Interface"),
	pointer_default(unique)
] 
#line 17 "c:\\source\\excel ldap search\\ldapquery\\cldapsearchresults.h"
interface ILdapSearchResults : IDispatch {
#line 19 "c:\\source\\excel ldap search\\ldapquery\\cldapsearchresults.h"
	[id(1),helpstring("method GetFirstResult")] HRESULT  GetFirstResult([out,retval] ILdapSearchResult **searchResult );
	[id(2),helpstring("method GetNextResult")] HRESULT  GetNextResult([out,retval] ILdapSearchResult **searchResult );
	[propget,id(3),helpstring("property ResultCount")] HRESULT  ResultCount([out,retval] LONG *pVal);
};

[
	object,
	uuid(14BEB14B-4CBB-4B10-918E-2D7F4E2AD414),
	dual,
	helpstring("IKnownAttributes Interface"),
	pointer_default(unique)
] 
#line 18 "c:\\source\\excel ldap search\\ldapquery\\knownattributes.h"
interface IKnownAttributes : IDispatch {
#line 20 "c:\\source\\excel ldap search\\ldapquery\\knownattributes.h"
	[propget,id(1),helpstring("property Count")] HRESULT  Count([out,retval] LONG *pVal);
	[propget,id(2),helpstring("property HumanName")] HRESULT  HumanName([in] LONG i, [out,retval] BSTR *pVal );
	[propget,id(3),helpstring("property LdapName")] HRESULT  LdapName([in] LONG i, [out,retval] BSTR *pVal );
};

[
	object,
	uuid(15CD66E6-F960-474A-81E7-42480262F9D5),
	dual,
	helpstring("ILdapConfig Interface"),
	pointer_default(unique)
] 
#line 16 "c:\\source\\excel ldap search\\ldapquery\\ldapconfig.h"
interface ILdapConfig : IDispatch {
#line 18 "c:\\source\\excel ldap search\\ldapquery\\ldapconfig.h"
	[id(1),helpstring("method Load")] HRESULT  Load([out,retval] SHORT *success);
	[propget,id(2),helpstring("property ServerName")] HRESULT  ServerName([out,retval] BSTR *pVal );
	[propput,id(2),helpstring("property ServerName")] HRESULT  ServerName([in] BSTR newVal);
	[propget,id(3),helpstring("property ServerPort")] HRESULT  ServerPort([out,retval] SHORT *pVal);
	[propput,id(3),helpstring("property ServerPort")] HRESULT  ServerPort([in] SHORT newVal);
	[propget,id(4),helpstring("property BindDN")] HRESULT  BindDN([out,retval] BSTR *pVal );
	[propput,id(4),helpstring("property BindDN")] HRESULT  BindDN([in] BSTR newVal);
	[propget,id(5),helpstring("property BindPW")] HRESULT  BindPW([out,retval] BSTR *pVal );
	[propput,id(5),helpstring("property BindPW")] HRESULT  BindPW([in] BSTR newVal);
	[propget,id(6),helpstring("property BaseDN")] HRESULT  BaseDN([out,retval] BSTR *pVal );
	[propput,id(6),helpstring("property BaseDN")] HRESULT  BaseDN([in] BSTR newVal);
	[id(7),helpstring("method GetKnownAttributes")] HRESULT  GetKnownAttributes([out,retval] IKnownAttributes **pKnownAttributes );
};

[
	object,
	uuid(92857390-9ECC-44F9-937F-61496EE9D2CB),
	dual,
	helpstring("ILdapSearch Interface"),
	pointer_default(unique)
] 
#line 20 "c:\\source\\excel ldap search\\ldapquery\\ldapsearch.h"
interface ILdapSearch : IDispatch {
#line 22 "c:\\source\\excel ldap search\\ldapquery\\ldapsearch.h"
	[id(1),helpstring("method ConnectAnon")] HRESULT  ConnectAnon([in] BSTR serverName, [out,retval] SHORT *connOK);
	[id(2),helpstring("method Connect")] HRESULT  Connect([in] BSTR serverName, [in] BSTR userName, [in] BSTR userPassword, [out,retval] SHORT *connOK);
	[id(3),helpstring("method Search")] HRESULT  Search([in] BSTR baseDN, [in] BSTR filter, [out,retval] LONG *count);
	[id(4),helpstring("method GetSearchResults")] HRESULT  GetSearchResults([out,retval] ILdapSearchResults **searchResults );
	[propget,id(5),helpstring("property ErrorString")] HRESULT  ErrorString([out,retval] BSTR *pVal );
};

[
	object,
	uuid(E0302633-7070-4BA6-8497-9E34C6817BF8),
	dual,
	helpstring("ILdapTreeBrowser Interface"),
	pointer_default(unique)
] 
#line 36 "c:\\source\\excel ldap search\\ldapquery\\ldaptreebrowser.h"
interface ILdapTreeBrowser : IDispatch {
#line 38 "c:\\source\\excel ldap search\\ldapquery\\ldaptreebrowser.h"
	[propget,id(1),helpstring("property SelectedDN")] HRESULT  SelectedDN([out,retval] BSTR *pVal );
};


[ version(1.0), uuid(CB337CA3-322B-4CB4-8E9F-32B598B85538), helpstring("LdapQuery 1.0 Type Library") ]
library LdapQuery
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(39348AAC-8BF6-4E88-A981-3F4C634F9216),
		helpstring("LdapAttribute Class")
	] 
#line 36 "c:\\source\\excel ldap search\\ldapquery\\ldapattribute.h"
	coclass CLdapAttribute {
		interface ILdapAttribute;
	};

	[
		version(1.0),
		uuid(29D51429-9BF3-4F9E-96C8-F0A4DCEE9711),
		helpstring("LdapSearchResult Class")
	] 
#line 39 "c:\\source\\excel ldap search\\ldapquery\\ldapsearchresult.h"
	coclass CLdapSearchResult {
		interface ILdapSearchResult;
	};

	[
		version(1.0),
		uuid(CB48D04A-E554-4677-A6F8-A844D587B439),
		helpstring("CLdapSearchResults Class")
	] 
#line 37 "c:\\source\\excel ldap search\\ldapquery\\cldapsearchresults.h"
	coclass CLdapSearchResults {
		interface ILdapSearchResults;
	};

	[
		version(1.0),
		uuid(D4469939-EFEB-4943-8F64-DA16008A012E),
		helpstring("KnownAttributes Class")
	] 
#line 38 "c:\\source\\excel ldap search\\ldapquery\\knownattributes.h"
	coclass CKnownAttributes {
		interface IKnownAttributes;
	};

	[
		version(1.0),
		uuid(21ADC129-68E2-4BFF-AB74-5126B74E12D6),
		helpstring("LdapConfig Class")
	] 
#line 45 "c:\\source\\excel ldap search\\ldapquery\\ldapconfig.h"
	coclass CLdapConfig {
		interface ILdapConfig;
	};

	[
		version(1.0),
		uuid(13A5BB19-93E3-4825-AD43-5240B5ED109F),
		helpstring("LdapSearch Class")
	] 
#line 42 "c:\\source\\excel ldap search\\ldapquery\\ldapsearch.h"
	coclass CLdapSearch {
		interface ILdapSearch;
	};

	[
		version(1.0),
		uuid(9C0C5764-9B9A-40D4-9973-0C24589F5184),
		helpstring("LdapTreeBrowser Class")
	] 
#line 53 "c:\\source\\excel ldap search\\ldapquery\\ldaptreebrowser.h"
	coclass CLdapTreeBrowser {
		interface ILdapTreeBrowser;
	};

}

